window.BRAINROT_CONFIG = {
  storageKey: 'brainrot_h5_mvp_save_v3_empty_slots',
  initialCoins: 25,
  defaultStarterSlotEnabled: false,
  starterTemplateId: 'br_01',
  starterSlotIndex: 0,
  maxSlots: 10,
  conveyorVisibleCount: 5,
  conveyorSpeed: 74,
  conveyorItemSize: 74,
  conveyorGap: 22,
  purchaseAnimDuration: 0.72,
  collectRadius: 54,
  collectCooldownSeconds: 3,
  playerSpeed: 230,
  autosaveInterval: 2.0,
  conveyorBrainrotIds: [
    'br_02',
    'br_03',
    'br_04',
    'br_05',
    'br_06',
    'br_07',
    'br_08',
    'br_09',
    'br_10',
    'br_11',
    'br_12'
  ],
  brainrots: [
    {
      id: 'br_01',
      order: 1,
      name: '小香蕉',
      quality: '普通',
      price: 0,
      incomePerSecond: 1,
      paybackSeconds: 0,
      designRole: '初始白送',
      imageSrc: 'assets/images/brainrots/little_banana.png',
      color: '#ffe36b'
    },
    {
      id: 'br_02',
      order: 2,
      name: '破香蕉',
      quality: '普通',
      price: 25,
      incomePerSecond: 2,
      paybackSeconds: 12.5,
      designRole: '新手第一次购买',
      imageSrc: 'assets/images/brainrots/broken_banana.png',
      color: '#f2c84b'
    },
    {
      id: 'br_03',
      order: 3,
      name: '樱桃小三',
      quality: '普通',
      price: 180,
      incomePerSecond: 5,
      paybackSeconds: 36,
      designRole: '快速爽点',
      imageSrc: 'assets/images/brainrots/cherry_mistress.png',
      color: '#ff4d73'
    },
    {
      id: 'br_04',
      order: 4,
      name: '焦哥',
      quality: '普通',
      price: 500,
      incomePerSecond: 9,
      paybackSeconds: 56,
      designRole: '前期稳定过渡',
      imageSrc: 'assets/images/brainrots/jiao_bro.png',
      color: '#c7793b'
    },
    {
      id: 'br_05',
      order: 5,
      name: '小柠檬',
      quality: '普通',
      price: 1200,
      incomePerSecond: 15,
      paybackSeconds: 80,
      designRole: '普通阶段目标',
      imageSrc: 'assets/images/brainrots/little_lemon.png',
      color: '#f7ff5a'
    },
    {
      id: 'br_06',
      order: 6,
      name: '小猕猴桃',
      quality: '稀有',
      price: 2800,
      incomePerSecond: 28,
      paybackSeconds: 100,
      designRole: '第一个稀有',
      imageSrc: 'assets/images/brainrots/little_kiwi.png',
      color: '#8bd44d'
    },
    {
      id: 'br_07',
      order: 7,
      name: '菠萝保安',
      quality: '稀有',
      price: 5500,
      incomePerSecond: 45,
      paybackSeconds: 122,
      designRole: '中期主力',
      imageSrc: 'assets/images/brainrots/pineapple_guard.png',
      color: '#ffa94a'
    },
    {
      id: 'br_08',
      order: 8,
      name: '草莓闺蜜',
      quality: '稀有',
      price: 9000,
      incomePerSecond: 72,
      paybackSeconds: 125,
      designRole: '稀有阶段核心',
      imageSrc: 'assets/images/brainrots/strawberry_bff.png',
      color: '#ff6a95'
    },
    {
      id: 'br_09',
      order: 9,
      name: '猕猴桃医生',
      quality: '稀有',
      price: 15000,
      incomePerSecond: 110,
      paybackSeconds: 136,
      designRole: '中后期加速',
      imageSrc: 'assets/images/brainrots/kiwi_doctor.png',
      color: '#78d85d'
    },
    {
      id: 'br_10',
      order: 10,
      name: '葡萄小三',
      quality: '史诗',
      price: 30000,
      incomePerSecond: 180,
      paybackSeconds: 167,
      designRole: '第一个大目标',
      imageSrc: 'assets/images/brainrots/grape_mistress.png',
      color: '#a56dff'
    },
    {
      id: 'br_11',
      order: 11,
      name: '榴莲小姐',
      quality: '史诗',
      price: 60000,
      incomePerSecond: 310,
      paybackSeconds: 194,
      designRole: '后期稳定追求',
      imageSrc: 'assets/images/brainrots/durian_lady.png',
      color: '#c0d943'
    },
    {
      id: 'br_12',
      order: 12,
      name: '香蕉女王',
      quality: '传说',
      price: 125000,
      incomePerSecond: 560,
      paybackSeconds: 223,
      designRole: '当前版本终局目标',
      imageSrc: 'assets/images/brainrots/banana_queen.png',
      color: '#ffd56a'
    }
  ]
};
